# Generated by Django 5.0.1 on 2024-04-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_available_balance_user_and_more'),
        ('marchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchantuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='marchantuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='marchantuser',
            name='username',
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='marchantuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='marchantuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestap', models.DateTimeField(auto_now_add=True)),
                ('available_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.available_balance')),
                ('ledger_balance_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ledger_balance')),
            ],
        ),
    ]
