# Generated by Django 5.0.1 on 2024-04-07 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0002_remove_marchantuser_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchantuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='marchantuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='marchantuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='marchantuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='marchantuser',
            name='password',
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='marchant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
