# Generated by Django 5.0.1 on 2024-04-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0003_remove_marchantuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchantuser',
            name='marchant',
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
