# Generated by Django 5.0.1 on 2024-04-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0007_marchantuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchantuser',
            name='user',
        ),
    ]
