# Generated by Django 5.0.1 on 2024-04-18 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0008_remove_marchantuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchantprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marchant.marchantuser')),
            ],
        ),
    ]
