# Generated by Django 5.0.1 on 2024-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0009_marchantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchantprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
