# Generated by Django 5.0.1 on 2024-04-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0011_alter_marchantprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarchantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='marchantnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marchant.marchantuser'),
        ),
        migrations.AlterField(
            model_name='marchantprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marchant.marchantuser'),
        ),
    ]
