# Generated by Django 5.0.1 on 2024-04-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marchant', '0012_marchantuser_alter_marchantnotification_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marchantprofile',
        ),
    ]
