# Generated by Django 5.0.1 on 2024-04-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_pendingtransaction_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='users',
        ),
    ]
