# Generated by Django 5.0.1 on 2024-04-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_pendingtransaction_users'),
        ('base', '0010_remove_available_balance_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='users',
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.userprofile'),
        ),
    ]
