# Generated by Django 5.0.1 on 2024-04-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_remove_pendingtransaction_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='profile',
        ),
    ]
