# Generated by Django 5.0.1 on 2024-04-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_pendingtransaction_message'),
        ('marchant', '0010_alter_marchantprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marchant.marchantprofile'),
        ),
    ]
