# Generated by Django 5.0.1 on 2024-04-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_pendingtransaction_user'),
        ('marchant', '0012_marchantuser_alter_marchantnotification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marchant.marchantuser'),
        ),
    ]
