# Generated by Django 5.0.1 on 2024-04-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_pendingtransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='user',
        ),
    ]
