# Generated by Django 5.0.1 on 2024-04-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_remove_pendingtransaction_user'),
        ('marchant', '0014_marchantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_approve', models.BooleanField(default=True)),
                ('pending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.pendingtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marchant.marchantuser')),
            ],
        ),
    ]
