# Generated by Django 5.0.1 on 2024-04-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_rename_approvetransaction_marchantapprovetransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchantapprovetransaction',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='marchantapprovetransaction',
            name='user',
        ),
    ]
