# Generated by Django 5.0.1 on 2024-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_marchantpendingtransaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchantapprovetransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marchantpendingtransaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
