# Generated by Django 5.0.1 on 2024-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_marchantapprovetransaction_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedtransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
