# Generated by Django 5.0.1 on 2024-04-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_available_balance_ledger_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ledger_balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
