# Generated by Django 5.0.1 on 2024-04-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_available_balance_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_balance',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ledger_balance',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
