# Generated by Django 5.0.1 on 2024-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_available_balance_slug_ledger_balance_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_balance',
            name='slug',
            field=models.SlugField(default='', editable=False, null=True, unique=True),
        ),
    ]
