# Generated by Django 5.0.1 on 2024-04-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_nairawallet_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactions',
        ),
    ]
