# Generated by Django 5.0.1 on 2024-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_usertimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimestamp',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
