# Generated by Django 5.0.1 on 2024-04-16 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_usertimestamp_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimestamp',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
