# Generated by Django 5.0.1 on 2024-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_usertimestamp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimestamp',
            name='timebool',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usertimestamp',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
