# Generated by Django 5.0.1 on 2024-04-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_usertimestamp_timebool_alter_usertimestamp_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertimestamp',
            old_name='timebool',
            new_name='is_timebool',
        ),
    ]
