# Generated by Django 5.0.1 on 2024-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_timebool_usertimestamp_is_timebool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertimestamp',
            name='is_timebool',
        ),
        migrations.AddField(
            model_name='usertimestamp',
            name='timebool',
            field=models.BooleanField(default=False),
        ),
    ]
