# Generated by Django 5.0.1 on 2024-04-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_usertimestamp_is_timebool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertimestamp',
            old_name='timebool',
            new_name='time_bool',
        ),
    ]
