# Generated by Django 5.0.1 on 2024-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_usertimestamp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimestamp',
            name='inputValue',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
