# Generated by Django 5.0.1 on 2024-04-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.available_balance'),
        ),
    ]
