# Generated by Django 5.0.1 on 2024-04-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_eur_wallet_gpb_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EUR_Wallet',
            new_name='EURWallet',
        ),
        migrations.RenameModel(
            old_name='GPB_Wallet',
            new_name='GPBWallet',
        ),
    ]
