# Generated by Django 5.0.1 on 2024-04-23 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='nin_photo',
            field=models.FileField(upload_to='nin/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='available_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.available_balance'),
        ),
    ]
