# Generated by Django 5.0.1 on 2024-04-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_kyc_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='user',
            new_name='user_profile',
        ),
    ]
