# Generated by Django 5.0.1 on 2024-04-24 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_user_kyc_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='DOB',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='Gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='information',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='nin',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(code='invalid NIN', message='NIN must contain only digits', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='nin_photo',
            field=models.FileField(blank=True, upload_to='nin/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='photo',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
