# Generated by Django 5.0.1 on 2024-04-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_kyc_user_profile_kyc_user_alter_kyc_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
